server:
  port: 8081
  servlet:
    context-path: /post-service

spring:
  application:
    name: post-service
  profiles:
    include: sql #,script
  jpa:
    properties:
      hibernate.default_schema: post_schema