server:
  port: 8081
#  servlet:
#    context-path: /post-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: post-service
  profiles:
    include: sql #,script
  jpa:
    properties:
      hibernate.default_schema: post_schema