server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  #    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: post-service
          uri: http://localhost:8081/
          predicates:
            - Path=/post-service/**

        - id: auth-service
          uri: http://localhost:8083/
          predicates:
            - Path=/auth-service/login


