server:
  port: 9000
spring:
  profiles:
    include: sql #,script

  cloud:
    gateway:
      routes:
        - id: post-service
          uri: http://localhost:8086/
          predicates:
            - Path=/post/**

        - id: auth-service
          uri: http://localhost:8085/
          predicates:
            - Path=/auth-service/login
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
