server:
  port: 9000

spring:
  profiles:
    include: sql #,script

  cloud:
    gateway:
      routes:
        - id: post-service
          uri: http://localhost:8086/
          predicates:
            - Path=/post-service/**
          filters:


#        - id: auth-service
#          uri: http://localhost:8085/
#          predicates:
#            - Path=/auth-service/**
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
