server:
  port: 9090

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8085/
          predicates:
            - Path=/auth-service/login
        - id: post
          uri: http://localhost:8088/
          predicates:
            - Path=/post-service/**