server:
  port: 8080
spring:
  profiles:
    include: sql #,script

  cloud:
    gateway:
      routes:
        - id: post-service
          uri: http://localhost:8081/
          predicates:
            - Path=/post/**

        - id: auth-service
          uri: http://localhost:8083/
          predicates:
            - Path=/auth/login
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
