#eureka.client.service-url.default-zone=http://localhost:8761/eureka


#secret key - should be encrypted
#jwt.secret=secretkey
#ignore null fields in json
#spring.jackson.default-property-inclusion=NON_NULL
#spring.cloud.compatibility-verifier.enabled=false
spring:
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: eureka
server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka
